version: '3'
services:

  db:
    image: "mysql:5.7.10"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "db"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['/bin/sh', '-c', 'npm i && npm start']
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    volumes:
      - .:/usr/app/backend
    ports:
      - "3001:3001"

networks:
  default:
    external:
      name: sky_com

